### ISSUE TITLE
error ejecutar Jmeter con la extencion mqmeter

### ISSUE THREAD

**Issue by madagama89** [JoseLuisSR/mqmeter#1]
Cuando genero el .jar y lo almaceno en la carpeta de ext de Jmeter y ejecuto el Jmeter me arroja el siguiente mensaje de error que se muestra en la imagen adjunta.

![Error Jmeter](https://user-images.githubusercontent.com/48021903/62263911-739b0c80-b3e3-11e9-9b2d-20187f7f03b6.PNG)

**Comment by JoseLuisSR** [comment]
Hola.

En la carpeta /lib o /lib/ext existen otras librerias de IBM MQ??

https://github.com/JoseLuisSR/mqmeter#troubleshooting

El .jar lo esta generando con mvn??

Puede agregar todo el stacktrace de la linea de comandos para tener más información y diagnosticar el problema.

Gracias!!!

**Comment by JoseLuisSR** [comment]
Hola.

No recibí respuesta con respecto a los .jar que esta en el PATH /lib o /lib/ext del área de trabajo loca de JMeter. Cierro este issue.
