### ISSUE TITLE
Confused about jar install

### ISSUE THREAD

**Issue by mazzoe2** [JoseLuisSR/mqmeter#2]
Hi Jose,

I think I’m confused about your mqmeter install.
What am I supposed to install in ./lib/ext?

When I unzip contents, I don’t find any jar files to place into ext folder, just some java.

In any event, jmeter complains about script...
Error creating class:’co.signal.mqmeter.MQClientSampler’ in JavaSampler Put/Get message, check for a missing jar in your jmeter ‘search paths’ and ‘plugin_dependency_paths’ properties.........classnotfoundexception: co.signal.mqmeter.MQClientSampler...

**Comment by JoseLuisSR** [comment]
Hi mazzoe2.

Sorry for the delay of my response.

The first step is build .jar file through maven. You can find instrucctions to install maven and build jar with the below link:

https://maven.apache.org/guides/getting-started/maven-in-five-minutes.html

The second step is take the mqmeter.jar file generated in the first step and put on /lib/ext jmeter folder that is in your workarea.

Follow the above steps and let me know any issue, or just said me if you need the  mqmeter.jar file and I can sent it to you.

Many thanks.

**Comment by JoseLuisSR** [comment]
Hi mazzoe2

I am going to close this because it is not a issue, is just an error because you didn't install mqmeter.jar on JMeter before use it.

Let me know if the setps describe in previously message worked for you.

Thanks.

**Comment by polypdp** [comment]
![image](https://user-images.githubusercontent.com/59284722/229850332-4762bcbb-56e5-4b71-9c58-c903792fabeb.png)

![image](https://user-images.githubusercontent.com/59284722/229850149-ce6f7cfb-48be-41dd-b4f5-87d8f9afa80f.png)
