### ISSUE TITLE
re-use queue opened to send multiple messages without open/close queue each time

### ISSUE THREAD

**Issue by pmirek** [JoseLuisSR/mqmeter#4]
Thanks for a great plugin. It saves a lot of time for playing with what was available so far.
Here goes my request for improvement of existing solution: can you implement re-using queues instead open/close for each sample? That will make sending/receiving messages over same queue faster.

It can be smth. like "open queue sampler", that gives the reference to the queue as a variable, that can be re-used by other samplers for sending messages and for sampler closing the queue when scenario is done.

So it could be flow similar to:
 * use 1st sampler to open communication:

        mqQueue = mqMgr.accessQueue(mq_Queue, MQConstants.MQOO_OUTPUT); 

    then pass  mqQueue as variable (object)
 * use it for sending messages
 * use it to conclude and close in the scenario end

        mqQueue.close();

**Comment by JoseLuisSR** [comment]
Hi pmirek.

Thanks a lot to use mqmeter and share your request and suggestion that is very good.

I did it, you can find the changes on develop branch (commit 81a92aad1994752db3b63df5258626c6067ef8ab), please pull the develop branch from your work area (git pull origin develop), test it and give me your feedback (issues or enhancements) to can merge it on master branch.

Regards.

**Comment by pmirek** [comment]
I've checked the develop branch for put message.
It looks good, ~3x faster in gui mode then old code.

* old one (2 TPS per 20 runs): 
  ![old 2 TPS](https://user-images.githubusercontent.com/21124881/69524294-fa14c480-0f65-11ea-9456-614b7dedfa85.png)

* new one (6.5 TPS per 20 runs):
  ![new 6 TPS](https://user-images.githubusercontent.com/21124881/69524328-0bf66780-0f66-11ea-9e1a-8cd4b3fdad7f.png)

Thanks for update!

**Comment by pmirek** [comment]
Done,

I've updated the issue with a short test results.

Thanks!

**Comment by pmirek** [comment]
BTW, have you thought about sharing your work with jmeter community over
here: https://jmeter-plugins.org/
Your sampler is definitely worth to be in well-known plugins repo.

Thanks!

**Comment by JoseLuisSR** [comment]
Hi @pmirek 

Sorry for the delay of my response.

Thanks to tested it and share your feedback. Your contribution was great.

I opened a topic to ask about the steps to publish it on jmete-plugins

https://groups.google.com/forum/#!topic/jmeter-plugins/gM0CzelmK-w

I will advise you when it be ready.

Thank you in advance.

**Comment by JoseLuisSR** [comment]
Hi @pmirek 

It is over https://jmeter-plugins.org/ with name "IBM MQ Support".

Could you please install and test it?

Please share the results.

Thank you
