### ISSUE TITLE
Windows userId is used instead the configured userId in the plugin

### ISSUE THREAD

**Issue by freddyschoeters** [JoseLuisSR/mqmeter#5]
When I execute the script with the configured plugin for putting a message on a queue, I get the error:
**2020-01-13 16:52:19,443 INFO c.s.m.MQClientSampler: setupTest MQJE001: Completion Code '2', Reason '2035'. MQRC_NOT_AUTHORIZED**

I pulled your code and added console logging for username and password and I see that the correct ones are used.
However, I installed Wireshark to see what the traffic is, and then I suddenly see that my Windows username is used.
Any ideas?

**Comment by freddyschoeters** [comment]
An update from my side: In the code of the plugin, I have put the property **MQConstants.USE_MQCSP_AUTHENTICATION_PROPERTY** to false and repackaged it and this seems to work now.
May be it's interesting to pass this as a parameter in the User Defined Variables as well?
I'll see if I can create a pull request as well (although, I made a change for our empty password as well)

**Comment by JoseLuisSR** [comment]
Hi @freddyschoeters 

Thank you to use mqmeter, find an issue and also resolve it.

Your contibution is appreciate to improve mqmeter.

Regards.

**Comment by ntran2020** [comment]
Wanted to inform you that this code update, addition of MQConstants.USE_MQCSP_AUTHENTICATION_PROPERTY, is not found in the version when pulled through  JMETER Plugin Manager.

**Comment by JoseLuisSR** [comment]
Hi @ntran2020 

You are right, it is not present in JMETER Plugin Manager yet.

I hope work on it in the next days, I will notify you any updates.

Thank you for your comment.
